### ISSUE TITLE
Include classNames of assets for future matching against squad logs.

### ISSUE THREAD

**Issue by codejunkienick** [frobinsonj/squad-json#1]
Currently SquadGameLog reports asset className 
it would be great to export a asset classNames to utilize it for matching like so  `"classNames": ["BP_Brit_Util_Truck_Woodland_C", "BP_Brit_Util_Truck_C"]`

https://github.com/fantinodavide/SquadLayerList/blob/main/layers.json has it but it is not in such convenient format as yours.

**Comment by frobinsonj** [comment]
Apologies for the delay @codejunkienick. Would adding a more generic `versions` property work for your use case?

```json
{
	"name": "HX60 Logistics",
	"versions": [
		{
			"class_name": "BP_Brit_Util_Truck_Logi_C",
			"path": "/Game/Vehicles/British_Util_Truck/BP_Brit_Util_Truck_Logi.BP_Brit_Util_Truck_Logi_C",
			"biomes": [
				"DESERT"
			]
		},
		{
			"class_name": "BP_Brit_Util_Truck_Logi_Woodland_C",
			"path": "/Game/Vehicles/British_Util_Truck/BP_Brit_Util_Truck_Logi_Woodland.BP_Brit_Util_Truck_Logi_Woodland_C",
			"biomes": [
				"FOREST",
				"SNOW"
			]
		}
	],
	"tickets": 5,
	"type": "LOGI",
	"tags": [
		"CLASS_HEAVY"
	],
	"icon": "icons/map/truck_logistics.png"
}

**Comment by frobinsonj** [comment]
Added class names in [v8.2.0](https://github.com/frobinsonj/squad-json/releases/tag/v8.2.0).
